setwd("~/")
setwd("Hindcasting-Methods/R")
source("Regressions.R")
source("PCAnEn.R")
setwd("~/")
setwd("Hindcasting-Methods/R/Load")
source("InterpolateData.R")
source("LoadData.R")
source("LoadStationCsv.R")
source("LoadStation.R")
source("OrganizeIntoDataframe.R")
setwd("~/")
setwd("Hindcasting-Methods/R/Load/PCA")
source("DoPCA.R")
source("DoPLS.R")
setwd("~/")
setwd("Hindcasting-Methods/R/organize")
source("OrganizeSequenceVectors.R")
setwd("~/")
setwd("Hindcasting-Methods/R/results")
source("CheckResults.R")
setwd("~/")
setwd("Hindcasting-Methods/R/methods")
source("Monache_PCA.R", local = TRUE)
source("ClustAnEn.R", local = TRUE)
